title: Configuration
data:
  error_404_entry: 059d4d8d-fc60-49f8-8823-7da10549e84e
  copyright_since: 2020
  privacy_statement_type: entry
  privacy_statement_entry: ef9e42b8-c092-49eb-a612-92ef826867b8
